In [402]:
import sklearn
from sklearn import datasets
import numpy as np

In [403]:
n_dim = 5
cov = sklearn.datasets.make_spd_matrix(n_dim, random_state=None)

In [404]:
mu = np.random.normal(0, 0.1, n_dim)

In [405]:
X = np.random.multivariate_normal(mu, cov, 500)

In [406]:
cov

array([[ 1.51050356,  0.0979012 , -1.3533993 ,  1.69652164,  0.12368509],
       [ 0.0979012 ,  0.38203196,  0.0838268 , -0.32166331,  0.1182334 ],
       [-1.3533993 ,  0.0838268 ,  1.70201001, -1.75043085,  0.03068494],
       [ 1.69652164, -0.32166331, -1.75043085,  3.04370879, -0.02026801],
       [ 0.12368509,  0.1182334 ,  0.03068494, -0.02026801,  0.52746562]])

In [407]:
np.cov(X.T)

array([[ 1.48408819,  0.0869628 , -1.37851651,  1.75915641,  0.11585292],
       [ 0.0869628 ,  0.37814901,  0.05120384, -0.31708924,  0.11503449],
       [-1.37851651,  0.05120384,  1.78657098, -1.87388981,  0.05312682],
       [ 1.75915641, -0.31708924, -1.87388981,  3.17433478, -0.04601059],
       [ 0.11585292,  0.11503449,  0.05312682, -0.04601059,  0.6029139 ]])

In [408]:
from sklearn.preprocessing import StandardScaler

In [409]:
scaler = StandardScaler().fit(X)

In [410]:
X_scaled = scaler.fit_transform(X)

In [411]:
np.mean(X_scaled[:,0])

-2.1316282072803006e-17

In [412]:
from sklearn import decomposition

In [413]:
pca = decomposition.PCA()

In [414]:
pca.fit(X_scaled)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [415]:
pca.explained_variance_

array([2.64588048, 1.31158911, 0.78598256, 0.18109259, 0.0854753 ])

In [416]:
pca_output = pca.fit_transform(X_scaled)

In [417]:
np.round(np.cov(pca_output.T), 2)

array([[ 2.65, -0.  ,  0.  ,  0.  ,  0.  ],
       [-0.  ,  1.31,  0.  , -0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.79,  0.  ,  0.  ],
       [ 0.  , -0.  ,  0.  ,  0.18, -0.  ],
       [ 0.  ,  0.  ,  0.  , -0.  ,  0.09]])

## Try a linear autoencoder to mimic PCA

In [418]:
import tensorflow as tf
from keras.models import Model, load_model
from keras.layers import Input, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras import regularizers

In [419]:
nb_epoch = 100
batch_size = 16
input_dim = X_scaled.shape[1] #num of predictor variables, 
encoding_dim = 2
learning_rate = 1e-3

input_layer = Input(shape=(input_dim, ))
encoder = Dense(encoding_dim, activation="linear", use_bias = False)(input_layer)
decoder = Dense(input_dim, activation="linear", use_bias = False)(encoder)
autoencoder = Model(inputs=input_layer, outputs=decoder)
autoencoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_24 (InputLayer)        (None, 5)                 0         
_________________________________________________________________
dense_113 (Dense)            (None, 2)                 10        
_________________________________________________________________
dense_114 (Dense)            (None, 5)                 10        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [420]:
autoencoder.compile(metrics=['accuracy'],
                    loss='mean_squared_error',
                    optimizer='adam')

history = autoencoder.fit(X_scaled, X_scaled,
                    epochs=nb_epoch,
                    batch_size=batch_size,
                    shuffle=True,
                    verbose=1).history

Epoch 1/100
500/500 [==============================] - 2s 3ms/step - loss: 1.3535 - acc: 0.1940
Epoch 2/100
500/500 [==============================] - 0s 79us/step - loss: 1.1982 - acc: 0.2320
Epoch 3/100
500/500 [==============================] - 0s 74us/step - loss: 1.0717 - acc: 0.2560
Epoch 4/100
500/500 [==============================] - 0s 78us/step - loss: 0.9652 - acc: 0.2780
Epoch 5/100
500/500 [==============================] - 0s 77us/step - loss: 0.8740 - acc: 0.3140
Epoch 6/100
500/500 [==============================] - 0s 75us/step - loss: 0.7949 - acc: 0.3380
Epoch 7/100
500/500 [==============================] - 0s 73us/step - loss: 0.7262 - acc: 0.3520
Epoch 8/100
500/500 [==============================] - 0s 73us/step - loss: 0.6674 - acc: 0.3640
Epoch 9/100
500/500 [==============================] - 0s 78us/step - loss: 0.6171 - acc: 0.3860
Epoch 10/100
500/500 [==============================] - 0s 74us/step - loss: 0.5740 - acc: 0.4100
Epoch 11/100
500/500 [========

500/500 [==============================] - 0s 75us/step - loss: 0.2137 - acc: 0.6320
Epoch 85/100
500/500 [==============================] - 0s 74us/step - loss: 0.2134 - acc: 0.6320
Epoch 86/100
500/500 [==============================] - 0s 72us/step - loss: 0.2133 - acc: 0.6320
Epoch 87/100
500/500 [==============================] - 0s 73us/step - loss: 0.2131 - acc: 0.6320
Epoch 88/100
500/500 [==============================] - 0s 74us/step - loss: 0.2130 - acc: 0.6320
Epoch 89/100
500/500 [==============================] - 0s 73us/step - loss: 0.2129 - acc: 0.6300
Epoch 90/100
500/500 [==============================] - 0s 72us/step - loss: 0.2126 - acc: 0.6320
Epoch 91/100
500/500 [==============================] - 0s 74us/step - loss: 0.2125 - acc: 0.6280
Epoch 92/100
500/500 [==============================] - 0s 73us/step - loss: 0.2124 - acc: 0.6320
Epoch 93/100
500/500 [==============================] - 0s 72us/step - loss: 0.2122 - acc: 0.6320
Epoch 94/100
500/500 [===========

In [421]:
np.round(autoencoder.layers[1].get_weights(), 2)

array([[[-0.6 ,  0.44],
        [-0.88, -0.15],
        [-0.01, -0.41],
        [ 0.13,  0.4 ],
        [-0.72, -0.06]]], dtype=float32)

In [422]:
np.round(autoencoder.layers[2].get_weights(), 2)

array([[[-0.25, -0.57,  0.07,  0.05, -0.47],
        [ 0.73, -0.27, -0.77,  0.79, -0.12]]], dtype=float32)

In [423]:
pca.components_

array([[ 0.57542321, -0.0823935 , -0.57578763,  0.57494914,  0.00123692],
       [-0.21854994, -0.71220901,  0.01300828,  0.13110063, -0.6539401 ],
       [ 0.10062666,  0.62637442, -0.13465058, -0.14418562, -0.74740156],
       [-0.17979115, -0.15745114, -0.75680923, -0.6007439 ,  0.09607725],
       [ 0.7607059 , -0.26236209,  0.27822364, -0.52015708, -0.0672375 ]])

In [424]:
pca.explained_variance_ratio_

array([0.52811774, 0.26179319, 0.15688212, 0.03614608, 0.01706087])

In [425]:
intermediate_layer = Model(inputs=autoencoder.inputs, outputs=autoencoder.layers[1].output)

In [426]:
intermediate_output = intermediate_layer.predict(X_scaled)

In [427]:
intermediate_output.shape

(500, 2)

In [428]:
aa = np.array(intermediate_output)

In [429]:
cc = np.cov(aa.T)

In [430]:
cc

array([[ 2.15649179, -0.20868458],
       [-0.20868458,  1.42645623]])

In [431]:
aa_scaler = StandardScaler().fit(aa)

In [432]:
aa_scaled = aa_scaler.fit_transform(aa)

In [433]:
pca0 = decomposition.PCA()

In [434]:
pca0.fit(aa_scaled)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [435]:
pca0.explained_variance_ratio_

array([0.5594918 , 0.44050822], dtype=float32)

----

In [1430]:
from keras.layers import Layer, InputSpec
from keras import activations, initializers, constraints, Sequential
from keras import backend as K
from keras.constraints import UnitNorm

# Reference: https://stackoverflow.com/questions/53751024/tying-autoencoder-weights-in-a-dense-keras-layer
class DenseTied(Layer):
    def __init__(self, units,
                 activation=None,
                 use_bias=True,
                 kernel_initializer='glorot_uniform',
                 bias_initializer='zeros',
                 kernel_regularizer=None,
                 bias_regularizer=None,
                 activity_regularizer=None,
                 kernel_constraint=None,
                 bias_constraint=None,
                 tied_to=None,
                 **kwargs):
        self.tied_to = tied_to
        if 'input_shape' not in kwargs and 'input_dim' in kwargs:
            kwargs['input_shape'] = (kwargs.pop('input_dim'),)
        super().__init__(**kwargs)
        self.units = units
        self.activation = activations.get(activation)
        self.use_bias = use_bias
        self.kernel_initializer = initializers.get(kernel_initializer)
        self.bias_initializer = initializers.get(bias_initializer)
        self.kernel_regularizer = regularizers.get(kernel_regularizer)
        self.bias_regularizer = regularizers.get(bias_regularizer)
        self.activity_regularizer = regularizers.get(activity_regularizer)
        self.kernel_constraint = constraints.get(kernel_constraint)
        self.bias_constraint = constraints.get(bias_constraint)
        self.input_spec = InputSpec(min_ndim=2)
        self.supports_masking = True
        
#     def __init__(self, units,
#              activation=None,
#              use_bias=True,
#              kernel_initializer='glorot_uniform',
#              bias_initializer='zeros',
#              kernel_regularizer=None,
#              bias_regularizer=None,
#              activity_regularizer=None,
#              kernel_constraint=None,
#              bias_constraint=None,
#              tied_to=None,
#              **kwargs):
#         if 'input_shape' not in kwargs and 'input_dim' in kwargs:
#             kwargs['input_shape'] = (kwargs.pop('input_dim'),)
#         super(Dense, self).__init__(**kwargs)
#         self.units = units
#         self.activation = activations.get(activation)
#         self.use_bias = use_bias
#         self.kernel_initializer = initializers.get(kernel_initializer)
#         self.bias_initializer = initializers.get(bias_initializer)
#         self.kernel_regularizer = regularizers.get(kernel_regularizer)
#         self.bias_regularizer = regularizers.get(bias_regularizer)
#         self.activity_regularizer = regularizers.get(activity_regularizer)
#         self.kernel_constraint = constraints.get(kernel_constraint)
#         self.bias_constraint = constraints.get(bias_constraint)
#         self.input_spec = InputSpec(min_ndim=2)
#         self.supports_masking = True
#         self.tied_to = tied_to

#     def build(self, input_shape):
#         assert len(input_shape) >= 2
#         input_dim = input_shape[-1]

#         if self.tied_to is not None:
#             self.kernel = K.transpose(self.tied_to.kernel)
#             self._non_trainable_weights.append(self.kernel)
#         else:
#             self.kernel = self.add_weight(shape=(input_dim, self.units),
#                                           initializer=self.kernel_initializer,
#                                           name='kernel',
#                                           regularizer=self.kernel_regularizer,
#                                           constraint=self.kernel_constraint)
#         if self.use_bias:
#             self.bias = self.add_weight(shape=(self.units,),
#                                         initializer=self.bias_initializer,
#                                         name='bias',
#                                         regularizer=self.bias_regularizer,
#                                         constraint=self.bias_constraint)
#         else:
#             self.bias = None

#         self.built = True
        
    def build(self, input_shape):
        assert len(input_shape) >= 2
        input_dim = input_shape[-1]

        if self.tied_to is not None:
            self.kernel = K.transpose(self.tied_to.kernel)
            self._non_trainable_weights.append(self.kernel)
        else:
            self.kernel = self.add_weight(shape=(input_dim, self.units),
                                          initializer=self.kernel_initializer,
                                          name='kernel',
                                          regularizer=self.kernel_regularizer,
                                          constraint=self.kernel_constraint)
        if self.use_bias:
            self.bias = self.add_weight(shape=(self.units,),
                                        initializer=self.bias_initializer,
                                        name='bias',
                                        regularizer=self.bias_regularizer,
                                        constraint=self.bias_constraint)
        else:
            self.bias = None
        self.input_spec = InputSpec(min_ndim=2, axes={-1: input_dim})
        self.built = True

    def compute_output_shape(self, input_shape):
        assert input_shape and len(input_shape) >= 2
#         assert input_shape[-1] == self.units
        output_shape = list(input_shape)
        output_shape[-1] = self.units
        return tuple(output_shape)

    def call(self, inputs):
        output = K.dot(inputs, self.kernel)
        if self.use_bias:
            output = K.bias_add(output, self.bias, data_format='channels_last')
        if self.activation is not None:
            output = self.activation(output)
        return output

In [1479]:
# encoded1 = Dense(4, activation="sigmoid", input_shape=(4,), use_bias=True)
# decoded1 = DenseTied(4, activation="sigmoid", tied_to=encoded1, use_bias=False)

# # autoencoder
# #
# autoencoder = Sequential()
# # autoencoder.add(input_)
# autoencoder.add(encoded1)
# autoencoder.add(decoded1)

# autoencoder.compile(optimizer="adam", loss="binary_crossentropy")

# print(autoencoder.summary())

# autoencoder.fit(x=np.random.rand(100, 4), y=np.random.randint(0, 1, size=(100, 4)))

# print(autoencoder.layers[0].get_weights()[0])
# print(autoencoder.layers[1].get_weights()[0])

# input_ = Input(shape=(16,), dtype=np.float32)
# encoder
#

def fro_norm(w):
    return K.sqrt(K.sum(K.square(K.abs(w))))

def cust_reg(w):
    if(encoding_dim > 1):
        m = K.dot(K.transpose(w), w) - K.eye(encoding_dim)
        return fro_norm(m)
    else:
        m = K.sum(w ** 2) - 1.
        return m
    
nb_epoch = 100
batch_size = 16
input_dim = X_scaled.shape[1] #num of predictor variables, 
encoding_dim = 1
learning_rate = 1e-3
encoder = Dense(encoding_dim, activation="linear", input_shape=(input_dim,), use_bias = True, kernel_regularizer=cust_reg, kernel_constraint=UnitNorm(axis=0)) 
decoder = DenseTied(input_dim, activation="linear", tied_to=encoder, use_bias = False)

autoencoder = Sequential()
autoencoder.add(encoder)
autoencoder.add(decoder)

autoencoder.compile(metrics=['accuracy'],
                    loss='mean_squared_error',
                    optimizer='sgd')
autoencoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_142 (Dense)            (None, 1)                 6         
_________________________________________________________________
dense_tied_63 (DenseTied)    (None, 5)                 5         
Total params: 11
Trainable params: 6
Non-trainable params: 5
_________________________________________________________________


In [1484]:
autoencoder.fit(X_scaled, X_scaled,
                    epochs=nb_epoch,
                    batch_size=batch_size,
                    shuffle=True,
                    verbose=1)

Epoch 1/100
500/500 [==============================] - 0s 82us/step - loss: 0.4722 - acc: 0.4360
Epoch 2/100
500/500 [==============================] - 0s 92us/step - loss: 0.4722 - acc: 0.4180
Epoch 3/100
500/500 [==============================] - 0s 82us/step - loss: 0.4722 - acc: 0.4020
Epoch 4/100
500/500 [==============================] - 0s 86us/step - loss: 0.4722 - acc: 0.3980
Epoch 5/100
500/500 [==============================] - 0s 81us/step - loss: 0.4722 - acc: 0.4540
Epoch 6/100
500/500 [==============================] - 0s 88us/step - loss: 0.4722 - acc: 0.4020
Epoch 7/100
500/500 [==============================] - 0s 80us/step - loss: 0.4722 - acc: 0.4020
Epoch 8/100
500/500 [==============================] - 0s 80us/step - loss: 0.4721 - acc: 0.4180
Epoch 9/100
500/500 [==============================] - 0s 80us/step - loss: 0.4722 - acc: 0.4600
Epoch 10/100
500/500 [==============================] - 0s 82us/step - loss: 0.4723 - acc: 0.3980
Epoch 11/100
500/500 [=======

500/500 [==============================] - 0s 92us/step - loss: 0.4722 - acc: 0.4800
Epoch 85/100
500/500 [==============================] - 0s 92us/step - loss: 0.4722 - acc: 0.4480
Epoch 86/100
500/500 [==============================] - 0s 93us/step - loss: 0.4722 - acc: 0.4140
Epoch 87/100
500/500 [==============================] - 0s 94us/step - loss: 0.4721 - acc: 0.4240
Epoch 88/100
500/500 [==============================] - 0s 94us/step - loss: 0.4722 - acc: 0.4680
Epoch 89/100
500/500 [==============================] - 0s 93us/step - loss: 0.4722 - acc: 0.4180
Epoch 90/100
500/500 [==============================] - 0s 91us/step - loss: 0.4723 - acc: 0.4680
Epoch 91/100
500/500 [==============================] - 0s 89us/step - loss: 0.4721 - acc: 0.4240
Epoch 92/100
500/500 [==============================] - 0s 87us/step - loss: 0.4722 - acc: 0.4140
Epoch 93/100
500/500 [==============================] - 0s 80us/step - loss: 0.4723 - acc: 0.4000
Epoch 94/100
500/500 [===========

In [1485]:
print(np.round(np.transpose(autoencoder.layers[0].get_weights()[0]), 3))
print(np.round(autoencoder.layers[1].get_weights()[0], 3))



[[-0.573  0.084  0.579 -0.574 -0.007]]
[[-0.573  0.084  0.579 -0.574 -0.007]]


In [1475]:
# scipy.linalg.norm(np.transpose(autoencoder.layers[0].get_weights()[0]), 2)
np.sum(np.transpose(autoencoder.layers[0].get_weights()[0]) ** 2, axis = 1)

array([0.9999999], dtype=float32)

In [1464]:
np.round(pca.components_, 3)

array([[ 0.575, -0.082, -0.576,  0.575,  0.001],
       [-0.219, -0.712,  0.013,  0.131, -0.654],
       [ 0.101,  0.626, -0.135, -0.144, -0.747],
       [-0.18 , -0.157, -0.757, -0.601,  0.096],
       [ 0.761, -0.262,  0.278, -0.52 , -0.067]])

In [445]:
np.round(np.dot(pca.components_, np.transpose(pca.components_)), 2)

array([[ 1.,  0.,  0.,  0., -0.],
       [ 0.,  1., -0.,  0., -0.],
       [ 0., -0.,  1., -0.,  0.],
       [ 0.,  0., -0.,  1., -0.],
       [-0., -0.,  0., -0.,  1.]])

In [446]:
np.round(np.dot(autoencoder.layers[0].get_weights()[0], np.transpose(autoencoder.layers[0].get_weights()[0])), 2)

array([[ 1., -0.,  0.,  0.,  0.],
       [-0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -0., -0.],
       [ 0.,  0., -0.,  1., -0.],
       [ 0.,  0., -0., -0.,  1.]], dtype=float32)


-------

In [349]:
import numpy as np
from keras import backend as K
from keras.models import Sequential
from keras.layers import Dense, Activation

a_dim = 16
from keras import backend as K
def fro_norm(w):
    return K.sqrt(K.sum(K.square(K.abs(w))))

def cust_reg(w):
    print(w.shape[1])
    m = K.dot(K.transpose(w), w) - np.eye(a_dim)
    return fro_norm(m)

X = np.random.randn(100, 100)
y = np.random.randint(2, size=(100, 1))

model = Sequential()


# apply regularization here. applies regularization to the 
# output (activation) of the layer
model.add(Dense(a_dim, input_shape=(100,), 
                kernel_regularizer=cust_reg))
model.add(Dense(1))
model.add(Activation('softmax'))

model.compile(loss="binary_crossentropy",
              optimizer='sgd',
              metrics=['accuracy'])

model.fit(X, y, epochs=100, batch_size=32)

16
Epoch 1/100
100/100 [==============================] - 1s 13ms/step - loss: 13.0799 - acc: 0.4200
Epoch 2/100
100/100 [==============================] - 0s 78us/step - loss: 12.7055 - acc: 0.4200
Epoch 3/100
100/100 [==============================] - 0s 83us/step - loss: 12.3557 - acc: 0.4200
Epoch 4/100
100/100 [==============================] - 0s 70us/step - loss: 12.0283 - acc: 0.4200
Epoch 5/100
100/100 [==============================] - 0s 82us/step - loss: 11.7216 - acc: 0.4200
Epoch 6/100
100/100 [==============================] - 0s 72us/step - loss: 11.4338 - acc: 0.4200
Epoch 7/100
100/100 [==============================] - 0s 74us/step - loss: 11.1634 - acc: 0.4200
Epoch 8/100
100/100 [==============================] - 0s 70us/step - loss: 10.9091 - acc: 0.4200
Epoch 9/100
100/100 [==============================] - 0s 84us/step - loss: 10.6695 - acc: 0.4200
Epoch 10/100
100/100 [==============================] - 0s 69us/step - loss: 10.4436 - acc: 0.4200
Epoch 11/100
100

100/100 [==============================] - 0s 86us/step - loss: 9.2684 - acc: 0.4200
Epoch 85/100
100/100 [==============================] - 0s 67us/step - loss: 9.2687 - acc: 0.4200
Epoch 86/100
100/100 [==============================] - 0s 81us/step - loss: 9.2690 - acc: 0.4200
Epoch 87/100
100/100 [==============================] - 0s 72us/step - loss: 9.2693 - acc: 0.4200
Epoch 88/100
100/100 [==============================] - 0s 70us/step - loss: 9.2696 - acc: 0.4200
Epoch 89/100
100/100 [==============================] - 0s 70us/step - loss: 9.2698 - acc: 0.4200
Epoch 90/100
100/100 [==============================] - 0s 66us/step - loss: 9.2700 - acc: 0.4200
Epoch 91/100
100/100 [==============================] - 0s 76us/step - loss: 9.2701 - acc: 0.4200
Epoch 92/100
100/100 [==============================] - 0s 75us/step - loss: 9.2701 - acc: 0.4200
Epoch 93/100
100/100 [==============================] - 0s 71us/step - loss: 9.2701 - acc: 0.4200
Epoch 94/100
100/100 [===========

In [350]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_104 (Dense)            (None, 16)                1616      
_________________________________________________________________
dense_105 (Dense)            (None, 1)                 17        
_________________________________________________________________
activation_15 (Activation)   (None, 1)                 0         
Total params: 1,633
Trainable params: 1,633
Non-trainable params: 0
_________________________________________________________________


In [351]:
intermediate_layer = Model(inputs=model.inputs, outputs=model.layers[0].output)
intermediate_output = intermediate_layer.predict(X)

In [352]:
intermediate_output.shape

(100, 16)

In [353]:
np.round(np.dot(np.transpose(model.layers[0].get_weights()[0]), model.layers[0].get_weights()[0]), 2)

array([[ 1.01,  0.  ,  0.  , -0.  ,  0.  , -0.  , -0.  , -0.  , -0.  ,
        -0.  ,  0.  , -0.  , -0.  , -0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , -0.  ,  0.  ,  0.  , -0.  ,
         0.  , -0.  , -0.  ,  0.  , -0.  ,  0.  ,  0.  ],
       [-0.  ,  0.  ,  0.  ,  1.01,  0.  , -0.  ,  0.  , -0.  ,  0.  ,
        -0.  , -0.  ,  0.  , -0.  , -0.  , -0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , -0.  , -0.  , -0.  ,
        -0.  ,  0.  , -0.  , -0.  ,  0.  , -0.  ,  0.  ],
       [-0.  ,  0.  , -0.  , -0.  ,  0.  ,  1.01,  0.  ,  0.  , -0.  ,
         0.  , -0.  ,  0.  ,  0.  , -0.  , -0.  , -0.  ],
       [-0.  ,  0.  ,  0.  ,  0.  , -0.  ,  0.  ,  1.  , -0.  , -0.  ,
        -0.  , -0.  ,  0.  , -0.  , -0.  , -0.  ,  0.  ],
       [-0.  ,  0.  ,  0.  , -0.  , -0.  ,  0.  , -0.  ,  1.01, -0.  ,
         0.  ,  0.  , -0. 

In [354]:
model.layers[0].get_weights()[0].shape

(100, 16)

-------

# Solve PCA by reconstruction loss

In [448]:
import scipy
from scipy.optimize import minimize

In [449]:
scipy.linalg.norm(X_scaled, ord=2, axis=None, keepdims=False)

36.33585501444451

In [969]:
np.diag(np.cov(X_scaled.T))

array([1.00200401, 1.00200401, 1.00200401, 1.00200401, 1.00200401])

In [959]:
np.linalg.eig(np.cov(X_scaled.T))[0]

array([2.64588048, 1.31158911, 0.78598256, 0.0854753 , 0.18109259])

In [960]:
Vp = np.linalg.eig(np.cov(X_scaled.T))[1]

In [963]:
Z = np.dot(X_scaled, Vp)

In [967]:
np.round(np.cov(Z.T), 3)

array([[ 2.646,  0.   , -0.   , -0.   , -0.   ],
       [ 0.   ,  1.312,  0.   , -0.   , -0.   ],
       [-0.   ,  0.   ,  0.786,  0.   ,  0.   ],
       [-0.   , -0.   ,  0.   ,  0.085, -0.   ],
       [-0.   , -0.   ,  0.   , -0.   ,  0.181]])

In [962]:
np.dot(Vp, np.dot(np.dot(X_scaled.T, X_scaled), Vp.T)) /

array([[ 912.47769054,  165.98763746, -241.61287659,  -16.78774581,
        -481.97426312],
       [ 165.98763746,  342.23942029, -109.53662261,   32.68936889,
         112.62438902],
       [-241.61287659, -109.53662261,  465.6547657 ,  206.77787717,
          -4.85070314],
       [ -16.78774581,   32.68936889,  206.77787717,  178.62616209,
         -27.96399176],
       [-481.97426312,  112.62438902,   -4.85070314,  -27.96399176,
         601.00196138]])

In [1357]:
def reconstruction_error(x):
    V = x.reshape(-1, 5)
    loss = 0.1 * scipy.linalg.norm((X_scaled - np.dot(X_scaled, np.dot(np.transpose(V), V))), 2) / V.shape[0] + orthogonality_constraint(V) + norm_constraint(V) + max_variance(V)
    return loss

In [1358]:
pca.components_

array([[ 0.57542321, -0.0823935 , -0.57578763,  0.57494914,  0.00123692],
       [-0.21854994, -0.71220901,  0.01300828,  0.13110063, -0.6539401 ],
       [ 0.10062666,  0.62637442, -0.13465058, -0.14418562, -0.74740156],
       [-0.17979115, -0.15745114, -0.75680923, -0.6007439 ,  0.09607725],
       [ 0.7607059 , -0.26236209,  0.27822364, -0.52015708, -0.0672375 ]])

In [1359]:
reconstruction_error(pca.components_.flatten())

[2.64588048 1.31158911 0.78598256 0.0854753  0.18109259]
[2.64588048 1.31158911 0.78598256 0.18109259 0.0854753 ]


0.13522325525487686

In [1360]:
def orthogonality_constraint(V):
    return scipy.linalg.norm(np.dot(V, np.transpose(V)) - np.eye(V.shape[0]), 2)

In [1361]:
def norm_constraint(V):
    return scipy.linalg.norm(np.sum(V ** 2, axis = 1) - np.ones(V.shape[0]), 2)

In [1362]:
def max_variance(V):
    eigenvalues = np.linalg.eig(np.cov(X_scaled.T))[0][0:V.shape[0]]
    print(eigenvalues)
    Z_scores = np.dot(X_scaled, V.T)
    if(V.shape[0] > 1):
        Z_cov = np.diag(np.cov(Z_scores.T))
    else:
        Z_cov = np.cov(Z_scores.T)
    print(Z_cov)
    return scipy.linalg.norm(Z_cov - eigenvalues)

In [1363]:
orthogonality_constraint(pca.components_)

6.981230178556928e-16

In [1364]:
pca_reduced = decomposition.PCA(n_components=2)

In [1365]:
pca_reduced.fit(X_scaled)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [1366]:
pca_reduced.explained_variance_

array([2.64588048, 1.31158911])

In [1367]:
reconstruction_error(pca_reduced.components_)

[2.64588048 1.31158911]
[2.64588048 1.31158911]


0.9902086842977708

In [1368]:
pca_reduced.components_.shape

(2, 5)

In [1369]:
scipy.linalg.norm(X_scaled)

49.99999999999999

In [1370]:
orthogonality_constraint(pca_reduced.components_)

3.476735048214707e-16

In [1397]:
# minimize(reconstruction_error, x0 = pca_reduced.components_.flatten())
# result = minimize(reconstruction_error, x0 = np.random.normal(0, 1, len(pca_reduced.components_.flatten())))
# result = minimize(reconstruction_error, x0 = np.random.normal(0, 1, 5))
# result = minimize(reconstruction_error, x0 = np.zeros(5), method='Nelder-Mead')
result = minimize(reconstruction_error, x0 = np.random.normal(0, 1, 5), method='Nelder-Mead')

[2.64588048]
12.709724140956093
[2.64588048]
13.201030603397726
[2.64588048]
12.963276706117949
[2.64588048]
13.185991116089346
[2.64588048]
12.747436119773973
[2.64588048]
12.74300642566949
[2.64588048]
12.564263198728224
[2.64588048]
12.267292115715172
[2.64588048]
12.182404385737996
[2.64588048]
11.701521759936078
[2.64588048]
11.902795531892481
[2.64588048]
11.396891784266412
[2.64588048]
11.581092321862945
[2.64588048]
11.137989398933316
[2.64588048]
10.399322938894295
[2.64588048]
10.300702974832447
[2.64588048]
9.25376777819446
[2.64588048]
9.501124883236852
[2.64588048]
9.1657655529231
[2.64588048]
8.048974879283152
[2.64588048]
8.008068670611651
[2.64588048]
7.109953014756209
[2.64588048]
5.706809012369791
[2.64588048]
5.998913528682459
[2.64588048]
4.558541534456868
[2.64588048]
5.006103733119091
[2.64588048]
3.9810819543199214
[2.64588048]
3.089415772542816
[2.64588048]
3.410065921910631
[2.64588048]
3.9607530245174325
[2.64588048]
3.524669433824351
[2.64588048]
3.0689102152

[2.64588048]
2.645827107755051
[2.64588048]
2.6457485559213922
[2.64588048]
2.645689640769719
[2.64588048]
2.645775110888916
[2.64588048]
2.64576468407889
[2.64588048]
2.6458025520350748
[2.64588048]
2.6457361975538727
[2.64588048]
2.645701980501129
[2.64588048]
2.6457127118079686
[2.64588048]
2.6456276599673525
[2.64588048]
2.6455327859512017
[2.64588048]
2.6457173691194553
[2.64588048]
2.6455543728102953
[2.64588048]
2.645434420880188
[2.64588048]
2.6454791408152984
[2.64588048]
2.645479016485007
[2.64588048]
2.6453693948146153
[2.64588048]
2.645246516914669
[2.64588048]
2.645123524306527
[2.64588048]
2.645168972520307
[2.64588048]
2.645026495475292
[2.64588048]
2.6450173536933237
[2.64588048]
2.6448116664555363
[2.64588048]
2.6447719828423004
[2.64588048]
2.6444820469789847
[2.64588048]
2.6445224243073855
[2.64588048]
2.6445446204606573
[2.64588048]
2.6443955434777915
[2.64588048]
2.6440846632588393
[2.64588048]
2.643708675349552
[2.64588048]
2.6437500485375227
[2.64588048]
2.643774

In [1398]:
result.x

array([-0.58947845,  0.0956696 ,  0.58970625, -0.54332439, -0.02019066])

In [1399]:
orthogonality_constraint(result.x.reshape(-1, 5))

2.9645703891745256e-08

In [1400]:
np.sum(result.x.reshape(-1, 5) ** 2, axis = 1)

array([1.00000003])

In [1401]:
result.x.reshape(-1, 5)

array([[-0.58947845,  0.0956696 ,  0.58970625, -0.54332439, -0.02019066]])

In [1402]:
max_variance(result.x.reshape(-1, 5))

[2.64588048]
2.6413217308315957


0.004558749390316308

In [1396]:
result

 final_simplex: (array([[ 0.57537977, -0.08233875, -0.57579062,  0.57499768,  0.00113708],
       [ 0.57543113, -0.08231884, -0.5758173 ,  0.57492259,  0.00105158],
       [ 0.57541779, -0.08233055, -0.57573594,  0.57501552,  0.00116234],
       [ 0.57539854, -0.08231482, -0.57573352,  0.57503957,  0.00109954],
       [ 0.57546944, -0.08238281, -0.57576588,  0.57492643,  0.00111109],
       [ 0.57546096, -0.08228142, -0.57577221,  0.57494322,  0.00105704]]), array([2.55828653, 2.55828654, 2.55828654, 2.55828654, 2.55828656,
       2.55828656]))
           fun: 2.558286531515811
       message: 'Optimization terminated successfully.'
          nfev: 850
           nit: 541
        status: 0
       success: True
             x: array([ 0.57537977, -0.08233875, -0.57579062,  0.57499768,  0.00113708])

In [531]:
x = pca_reduced.components_.flatten()

In [532]:
print(x)

[ 0.57542321 -0.0823935  -0.57578763  0.57494914  0.00123692 -0.21854994
 -0.71220901  0.01300828  0.13110063 -0.6539401 ]


In [492]:
pca_reduced.components_

array([[ 0.57542321, -0.0823935 , -0.57578763,  0.57494914,  0.00123692],
       [-0.21854994, -0.71220901,  0.01300828,  0.13110063, -0.6539401 ]])

In [535]:
V1 = x.reshape(-1, 5)

In [540]:
np.sum(V1 ** 2, axis=1)

array([1., 1.])

In [541]:
V2 = result.x.reshape(-1, 5)

In [566]:
np.sum(V2 ** 2, axis = 1) - np.ones(V2.shape[0])

array([ 0.01719766, -0.01719765])

In [560]:
scipy.linalg.norm(np.sum(V2 ** 2, axis = 1) - np.ones(V2.shape[0]), 2)

0.024321158042332734

In [571]:
np.sqrt(0.01719766 ** 2 + (0.01719765 ** 2))

0.024321156942014498

In [563]:
a = np.array([1, 2, 3])

In [568]:
scipy.linalg.norm(a, 2)

3.7416573867739413

In [569]:
np.sqrt((1 ** 2 + 2 ** 2 + 3 ** 2))

3.7416573867739413

In [562]:
0.01719766 ** 2

0.0002957595094756

In [570]:
(-0.01719765 ** 2)

-0.00029575916552249993

In [ ]:
np.linalg.eig(cc)[0]